Items:
  - COAL_ORE
  - COAL
  - COAL_BLOCK
  
  - IRON_ORE
  - IRON_INGOT
  - IRON_BLOCK
  - IRON_NUGGET
  
  - GOLD_ORE
  - GOLD_INGOT
  - GOLD_BLOCK
  - GOLD_NUGGET
  
  - LAPIS_ORE
  - LAPIS_LAZULI
  - LAPIS_BLOCK
  
  - REDSTONE_ORE
  - REDSTONE
  - REDSTONE_BLOCK
  
  - DIAMOND_ORE
  - DIAMOND
  - DIAMOND_BLOCK
  
  - EMERALD_ORE
  - EMERALD
  - EMERALD_BLOCK
  
  - ANCIENT_DEBRIS
  - NETHERITE_SCRAP
  - NETHERITE_INGOT
  - NETHERITE_BLOCK